name: Publish Helm chart documentation

on:
  push:
    branches:
      - main

jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout documentation repository
        uses: actions/checkout@v2
        with:
          repository: JakeSCahill/redpanda-docs-antora
          ref: dev
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install helm-docs
        run: |
          wget https://github.com/norwoodj/helm-docs/releases/download/v1.11.0/helm-docs_1.11.0_Linux_arm64.tar.gz
          tar xzf helm-docs_1.11.0_Linux_arm64.tar.gz
          sudo install helm-docs /usr/local/bin/helm-docs
          
      - name: Generate documentation
        run: |
          cd helm-charts
          helm-docs

      - name: Commit documentation changes
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Action Bot"
          git add docs/reference/
          git commit -m "Update Helm chart documentation"
          git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
